### ISSUE TITLE
Can this be used, for example, in a quantised version?

### ISSUE THREAD

**Issue by 0417keito** [crypto-code/MU-LLaMA#15]
Can this be used, for example, in a quantised version? I tried to do inference, but it is out of memory and cannot be used.

**Comment by shansongliu** [comment]
Currently we haven't implemented quantized version of our MU-LLaMA model. Welcome to make a pull request if you plan to do so. Now the working version is 1 minute music file inferenced on a 32GB V100 GPU.

> Can this be used, for example, in a quantised version? I tried to do inference, but it is out of memory and cannot be used.

**Comment by 0417keito** [comment]
Thank you for your reply. Noted.

**Comment by 0417keito** [comment]
I propose LLaSA, which leverages the generic architecture of LLaVA to align different features, making it compatible with features like MERT and HuBERT. I believe this can lead to a multi-modal LLM that can understand music and audio. What do you think?

[https://github.com/0417keito/LLaSA](https://t.co/6z7oTrdZnO)

**Comment by shansongliu** [comment]
> I propose LLaSA, which leverages the generic architecture of LLaVA to align different features, making it compatible with features like MERT and HuBERT. I believe this can lead to a multi-modal LLM that can understand music and audio. What do you think?
> 
> [https://github.com/0417keito/LLaSA](https://t.co/6z7oTrdZnO)

Yeah, I think this is possible.

**Comment by 0417keito** [comment]
I don't have the resources to train a 7B-level LLM. I might be able to train a 1.3B-level model, but I believe the accuracy would be lower. So, I really don't mean to be rude, but do you have the capacity to train this within the MU-LLaMA project?

**Comment by shansongliu** [comment]
> I don't have the resources to train a 7B-level LLM. I might be able to train a 1.3B-level model, but I believe the accuracy would be lower. So, I really don't mean to be rude, but do you have the capacity to train this within the MU-LLaMA project?

There are plenty of memory-saving methods which you may take a look at, such as gradient accumulation, FSDP, etc., which may help you resolve the memory issues. For the capacity you mentioned, I'm afraid we don't have extra time and resources to handle issues which are irrelavant to our project. Sorry for that.

**Comment by 0417keito** [comment]
Thank you for considering my request and for the valuable information. I apologize for any inconvenience my question may have caused. I sincerely wish you all success. Thank you.

**Comment by shansongliu** [comment]
> Thank you for considering my request and for the valuable information. I apologize for any inconvenience my question may have caused. I sincerely wish you all success. Thank you.

Not a big deal. If you have any further questions, I'm willing to response.
