### ISSUE TITLE
Distinguishing QA and captioning

### ISSUE THREAD

**Issue by joemzhao** [crypto-code/MU-LLaMA#28]
Hello!

Thanks for the nice work!
I'd like to ask how did you separate the QA and  the captioning subtasks? In EvalMusicQA.json, there is no information on this, but in the paper, Tab2 and Tab3 report QA and captioning results separately.

Thank you!

**Comment by shansongliu** [comment]
You can distinguish them by the questions. The captioning task's questions have been described in the paper. Please take a look.

**Comment by Ajyy** [comment]
Hi,

EvalMusicQA.json has 5040 pairs, but according to the paper, it should be 4500 pairs for Music QA. Also, in this [issue](https://github.com/shansongliu/MU-LLaMA/issues/21), you said the caption data is not released. So, I am confused about the exact data for Music QA and caption tasks.

Could you further explain how to distinguish QA and captioning data from EvalMusicQA.json? Thanks
